name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
    bump-version:
        steps:
          - uses: remorses/bump-version@js
            with:
              version_file: ./VERSION
              check-latest: true
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - run: npm install
          - run: npm check-rules
