  name: Bump version
  uses: remorses/bump-version@js
  on:
    pull_request:
      types:
      - closed
      branches:
      - main
  with:
      version_file: ./VERSION
  env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}