name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: remorses/bump-version@js
        with:
          version_file: ./VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}